# Generated by Django 3.1.1 on 2021-10-20 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrolled',
            fields=[
                ('id', models.CharField(default='C1', max_length=125, primary_key=True, serialize=False)),
                ('course_id', models.CharField(default='CID1', max_length=125)),
                ('user_id', models.CharField(default='AA1', max_length=125)),
                ('datetime_applied', models.CharField(default='September 11, 2021 | 1:00 PM', max_length=30)),
                ('datetime_enrolled', models.CharField(default='September 12, 2021 | 1:00 PM', max_length=30)),
                ('enrolment_processed_by', models.CharField(default='ADMIN1', max_length=125)),
                ('hours_duration', models.CharField(default='400', max_length=5)),
                ('status', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LoginForm',
            fields=[
                ('id', models.CharField(default='1', max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(default='username', max_length=50)),
                ('password', models.CharField(default='password', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('authentication_user_id', models.CharField(default='1', max_length=125)),
                ('firstname', models.CharField(default='Jessica', max_length=125)),
                ('lastname', models.CharField(default='Saludes', max_length=125)),
                ('middlename', models.CharField(default='Manahan', max_length=125)),
                ('name_extension', models.CharField(default=' ', max_length=5)),
                ('birthdate', models.CharField(default=' ', max_length=125)),
                ('complete_address', models.CharField(default=' ', max_length=125)),
                ('contact_number', models.CharField(default='09101111111', max_length=15)),
                ('email_address', models.CharField(default='user@user.com', max_length=225)),
                ('gender', models.CharField(default='n', max_length=1)),
                ('civil_status', models.CharField(blank=True, default='1', max_length=1, null=True)),
                ('datetime_registered', models.DateTimeField(default=datetime.datetime(2021, 10, 21, 3, 2, 25, 2288))),
                ('role_id', models.IntegerField(default=1)),
            ],
        ),
    ]
