# Generated by Django 3.1.1 on 2021-10-20 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20211021_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecords',
            name='datetime_registered',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 3, 47, 3, 760638)),
        ),
    ]
