from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name = "home"),
    path('login_admin', views.login_admin, name = "login_admin"),
    path('dashboard', views.dashboard, name = "dashboard"),
    path('applicants', views.applicants, name = "applicants"),
    path('enroll_student', views.enroll_student, name = "enroll_student"),
    path('applicants_print', views.applicants_print, name = "applicants_print"),
    path('declare_payment', views.declare_payment, name = "declare_payment"),
    path('students_admin', views.students_admin, name = "students_admin"),
    path('instructors', views.instructors, name = "instructors"),
    path('add_instructor', views.add_instructor, name = "add_instructor"),
    path('add_specialization', views.add_specialization, name = "add_specialization"),
    path('remove_specialization', views.remove_specialization, name = "remove_specialization"),
    path('admin_accounts', views.admin_accounts, name = "admin_accounts"),
    path('skills_assessments', views.skills_assessments, name = "skills_assessments"),   
    path('insert_data', views.insert_data, name = "insert_data"),
    path('insert_data_process', views.insert_data_process, name = "insert_data_process"),
    path('delete_data', views.delete_data, name = "delete_data"),
    path('delete_data_process', views.delete_data_process, name = "delete_data_process"),
    path('lessons_admin', views.lessons_admin, name = "lessons_admin"),
    path('add_lesson', views.add_lesson, name = "add_lesson"),
    path('add_lesson_detail', views.add_lesson_detail, name = "add_lesson_detail"),
    path('appointments_admin', views.appointments_admin, name = "appointments_admin"),   
    path('add_appointment', views.add_appointment, name = "add_appointment"),   
    path('add_timeschedule_appointment', views.add_timeschedule_appointment, name = "add_timeschedule_appointment"),   
    path('schedule_types', views.schedule_types, name = "schedule_types"),   
    path('add_schedule_type', views.add_schedule_type, name = "add_schedule_type"),   
    path('course_details', views.course_details, name = "course_details"),
    path('rooms', views.rooms, name = "rooms"),
    path('add_room', views.add_room, name = "add_room"),
    path('category_details_edit', views.category_details_edit, name = "category_details_edit"),
    path('category_type_details_edit', views.category_type_details_edit, name = "category_type_details_edit"),
    path('car_type_edit', views.car_type_edit, name = "car_type_edit"),
    path('website_images', views.website_images, name = "system_settings"),
    path('enrolment_prediction', views.enrolment_prediction, name = "enrolment_prediction"),
    path('skills_assessment_reports', views.skills_assessment_reports, name = "skills_assessment_reports"),
    path('system_settings', views.system_settings, name = "system_settings"),
    path('system_settings_update', views.system_settings_update, name = "system_settings_update"),
    path('driving_guidelines', views.driving_guidelines, name = "driving_guidelines"),   
    path('add_course', views.add_course, name = "add_course"),   
    path('add_category', views.add_category, name = "add_category"),   
    path('add_category_type', views.add_category_type, name = "add_category_type"),   
    path('add_car_type', views.add_car_type, name = "add_car_type"),   
    path('notifications_admin', views.notifications_admin, name = "notifications_admin"),   
    path('messages_admin', views.messages_admin, name = "messages_admin"),   
    path('profile_view_admin', views.profile_view_admin, name = "profile_view_admin"),   
    path('activity_log_admin', views.activity_log_admin, name = "activity_log_admin"),   
    path('profile_logout_admin', views.profile_logout_admin, name = "profile_logout_admin"),   
]